# Generated by Django 5.1.6 on 2025-02-08 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задачи", max_length=255, unique=True, verbose_name="Задача"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Ведите подробное описание задачи",
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "is_main_task",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, эта задача является основной или подзадачей",
                        verbose_name="Признак основной задачи",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="Введите крайний срок выполнения задачи", verbose_name="Срок выполнения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("В работе", "В работе"), ("Завершена", "Завершена")],
                        default="Создана",
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "executor",
                    models.ManyToManyField(
                        help_text="Выберите исполнителя(лей)",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель(ли)",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="task_tracker.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["deadline"],
            },
        ),
    ]
