# Generated by Django 5.1.6 on 2025-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0002_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("В работе", "В работе"),
                    ("На проверке", "На проверке"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                verbose_name="Статус задачи",
            ),
        ),
    ]
