# Generated by Django 5.1.6 on 2025-02-19 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0003_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                help_text="Выберите исполнителей", to=settings.AUTH_USER_MODEL, verbose_name="Исполнители"
            ),
        ),
    ]
