# Generated by Django 5.1.6 on 2025-02-20 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0004_alter_task_executor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите исполнителей",
                null=True,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
